### PR TITLE
C2LC-372: parameterised scene dimension minX and minY values.

### PR DESCRIPTION
**Pull request by the-t-in-rtf**
See [C2LC-372](https://issues.fluidproject.org/browse/C2LC-372) for details.

### CODE REVIEW

**Comment by chosww** [comment]
Thanks @the-t-in-rtf, the changes you made looks good, and it makes sense to make adjustment of 0.5 on where it is needed. There's one thing you forgot to update, and that is how the scene is drawn in Scene component; the scene is using min/max of boundaries to draw the scene, and translated x and y pos should be used to draw the scene. Also, the path is drawn incorrectly as well, so after you update those, I will take another look.

**Comment by the-t-in-rtf** [comment]
I updated the path drawing logic to also offset itself (and updated the associated tests).

**Comment by the-t-in-rtf** [comment]
Daniel also mentioned that the last row/column of the scene grid weren't being drawn, I'm fixing that now.

**Comment by the-t-in-rtf** [comment]
I fixed the outstanding issues I was aware of and updated with `develop-o.8`. There were (expectable) merge conflicts in updated tests that used the old syntax for creating scene dimensions.  There was also a test failure related to the previous change that I mistakenly thought was caused by the merge, but which is fixed in the last commit.

**Comment by the-t-in-rtf** [comment]
The last error was a test coverage threshold error and not a test failure.  I'll look into that in a bit.

**Comment by chosww** [comment]
Thanks @the-t-in-rtf, the changes look good, and draws the grid and path correctly. After the coverage issue is fixed, this PR is good for @sbates-idrc to review.

**Comment by the-t-in-rtf** [comment]
As discussed in [C2LC-349](https://github.com/codelearncreate/c2lc-coding-environment/pull/166#issuecomment-833455971):

> The CI build failures were because of "branch" coverage changes, namely not reaching the conditional in the Scene that is configured for zero width and zero height scene dimensions. I fixed it by removing that conditional, which is unreachable because we cannot create a zero width or zero height scene using the update scene dimensions class.

**Pull request merged**
