### PR TITLE
C2LC-366: Fixed announcement when replace button is hit and no command is selected.

### PR DESCRIPTION
**Pull request by the-t-in-rtf**
See [C2LC-366](https://issues.fluidproject.org/browse/C2LC-366) for more information.

### CODE REVIEW

**Comment by the-t-in-rtf** [comment]
The builds will likely fail intermittently until the fixes included in #81 are merged.

**Comment by chosww** [comment]
@the-t-in-rtf, could you merge in the latest 0.8 branch, now that #81 is merged?

**Comment by the-t-in-rtf** [comment]
Done, thanks for the reminder.

**Comment by the-t-in-rtf** [comment]
There was a legitimate test failure because the tests only expected the old behaviour.  I have updated them to match the new behaviour, and they pass now.

**Comment by chosww** [comment]
The changes look good, and the announcement works as expected in different browsers/OS combinations.

**Pull request merged**
