### PR TITLE
C2LC-468: Update the cancel button colour in modal components

### PR DESCRIPTION
**Pull request by chosww**
See [C2LC-468](https://issues.fluidproject.org/browse/C2LC-468) for details.

### CODE REVIEW

**Comment by the-t-in-rtf** [comment]
In the default, mixed, and dark themes, the "delete all" modal still has the old colour.

In the greyscale and high contrast themes, none of the cancel buttons have changed.

**Comment by chosww** [comment]
Updating delete all modal will be done in another PR.

**Comment by the-t-in-rtf** [comment]
Just to clarify, the colours are also wrong for the new modals in both the greyscale and contrast themes.

**Comment by chosww** [comment]
> Just to clarify, the colours are also wrong for the new modals in both the greyscale and contrast themes.

Confirmed with Sepideh that the button colours are correct in the grayscale and highcontrast themes.

**Comment by chosww** [comment]
This task is done in C2LC-480.

**Pull request closed without merging**
