### PR TITLE
C2LC-363: Remove bubbles on column and row headers

### PR DESCRIPTION
**Pull request by chosww**

### CODE REVIEW

**Comment by the-t-in-rtf** [comment]
See [C2LC-363](https://issues.fluidproject.org/browse/C2LC-363) for details.

**Comment by the-t-in-rtf** [comment]
This works as expected on both desktop browsers and the iOS simulator.  I tested at various screen widths and text zoom levels, it looks good and works well in all.   You can still scroll part of a label out of bounds, but that's to be expected, and there are no odd artefacts like the previous snippets of "bubble".

**Comment by the-t-in-rtf** [comment]
The code changes look good to me.

**Comment by sbates-idrc** [comment]
I'm seeing a light green outline around the Scene in the Dark, Grayscale, and High Contrast themes.

**Pull request merged**
