### PR TITLE
C2LC-282: Update button components to have consistent interaction styles

### PR DESCRIPTION
**Pull request by chosww**

### CODE REVIEW

**Comment by the-t-in-rtf** [comment]
For the future, I'd appreciate it if you'd include a description, usually I just link to the associated issue.  It makes it easier to figure out the context of the changes, and then is there for future reference as well.

Something like this is fine:

See [C2LC-282](https://issues.fluidproject.org/browse/C2LC-282) for details.

**Comment by the-t-in-rtf** [comment]
Sadly the ticket also lacks a description.  At a minimum, please summarise what you're changing and how I should be able to verify the change.

**Comment by the-t-in-rtf** [comment]
A short discussion of the goal here would really help, but in the mean time I tried out the preview and the live site to try and understand.  My sense is:

1. Light coloured elements like the button to clear the scene or program were not previously consistent.
2. This pull makes them all use the style that previously the "delete all program steps" button used, i.e. green highlighting with a black border.

Is that the goal?

**Comment by chosww** [comment]
@the-t-in-rtf you are right about that the issue should have some description. This work was to fix some button components' interaction styles to match others -- as you can see from the commit messages, PlayButton didn't have hover style, DeleteAll button didn't have disabled style, and RefreshButton didn't have hover style.

**Pull request merged**
