### PR TITLE
C2LC-485: Change the play control container colour in the dark theme

### PR DESCRIPTION
**Pull request by chosww**
See [C2LC-485](https://issues.fluidproject.org/browse/C2LC-485) for details.

### CODE REVIEW

**Comment by the-t-in-rtf** [comment]
The changes look good, both when the button(s) are clickable, and when they're not.

**Comment by sbates-idrc** [comment]
C2LC-540 has been merged into `develop-1.0`. Please merge `develop-1.0` into this PR branch and resolve any conflicts.

**Comment by sbates-idrc** [comment]
The Play area in the Default theme, should have the same colours s the Dark theme.

**Comment by sbates-idrc** [comment]
The focus indicator for the Stop button changes size between enabled and disabled in the Grayscale theme.

**Comment by chosww** [comment]
> The focus indicator on the Stop button has a larger gap than the Play button.

In Tony's C2LC-540 work that has merged, Tony has styled focus styles with 3 layers of box-shadows, which works fine for the play button, but is inconsistent with the play button, as the PlayButton is rendering the triangle with the outer circle. We should either update the play button to use just the triangle SVG and use the same s

**Comment by sbates-idrc** [comment]
I'm seeing some more issues with the styling:

- Default theme, enabled Stop button, gap between button and focus indicator is the wrong colour
- Grayscale theme, disabled Play button, the focus indicator is white rather than black
- High contrast theme, the focus indicator is not visible on the Play button
- High contrast theme, the focus indicator is not visible on the speed slider

**Comment by sbates-idrc** [comment]
I'm seeing some more issues with the styling:

- Default theme, enabled Stop button, gap between button and focus indicator is the wrong colour
- Grayscale theme, disabled Play button, the focus indicator is white rather than black
- High contrast theme, the focus indicator is not visible on the Play button
- High contrast theme, the focus indicator is not visible on the speed slider

**Comment by sbates-idrc** [comment]
Please update this PR with the latest `develop-1.0` and resolve conflicts.

**Pull request merged**
